title: "Hussain Asif's Microsoft Fabric/Power BI Blog"
description: "Deep dives into Microsoft Fabric, Power BI, and modern data analytics"
# baseurl: "/datablog"
url: "https://hussainasif.github.io"
theme: minima

github_username: HussainAsif

markdown: kramdown
highlighter: rouge